# Generated by Django 2.1.1 on 2018-11-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_geolocation_owner'),
    ]
"""
following generated by removing a unique together from geolocation class
caused a migration erros.  May not occur after Postgres 9.3
workaround is to delete the constraint from pg directly and comment this out.
"""
    # operations = [
    #     migrations.AlterUniqueTogether(
    #         name='geolocation',
    #         unique_together=set(),
    #     ),
    # ]
